# Generated by Django 2.1 on 2018-08-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('recipee', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=5000)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
