# Generated by Django 2.1 on 2018-08-22 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeModel',
            new_name='Yuser',
        ),
    ]
