# Generated by Django 2.1 on 2018-08-31 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipee', '0003_auto_20180822_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='image',
        ),
        migrations.RemoveField(
            model_name='items',
            name='video',
        ),
    ]
