# Generated by Django 2.0.7 on 2018-09-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipee', '0005_items_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
